"""
Setting parameter untuk koneksi ke database.
"""

_UNIT_CODE_ = "PCT1"
_UNIT_NAME_ = "PLTU Pacitan 1"
_USER_ = 'root'
_PASS_ = 'P@ssw0rd'
_IP_ = 'localhost:33006' # '192.168.32.6:3306'
_LOCAL_IP_ = '192.168.32.6'
_DB_NAME_ = 'db_bat_pct1'

"Setting parameter nama variabel"

WATCHDOG_TAG = "OPC.AW1002.1LSB.WATCHDOG_STS.BO02"
SAFEGUARD_TAG = "SAFEGUARD:COMBUSTION"

DESC_ENABLE_COPT = "Tag Enable COPT"
DESC_ENABLE_COPT_BT = "BURN TILT ENABLE"
DESC_ENABLE_COPT_SEC = "SEC AIR ENABLE"
DESC_ENABLE_COPT_MOT = "MILL OUTLET ENABLE"
DESC_ALARM = "Combustion Alarm"

TAG_COPT_ISCALLING = "TAG:COPT_is_calling"
OXYGEN_STEADY_STATE_LEVEL = 0.01
