"""
Setting parameter untuk koneksi ke database.
"""
__version__ = 'v1.3'

# _UNIT_CODE_ = "AMG2"
# _UNIT_NAME_ = "PLTU AMURANG (UNIT 2)"
# _DB_NAME_ = 'db_bat_amurang2'
# _IP_ = '192.168.1.12:3306'
# _LOCAL_IP_ = '192.168.1.12'

_UNIT_CODE_ = "AMG1"
_UNIT_NAME_ = "PLTU AMURANG (UNIT 1)"
_DB_NAME_ = 'db_bat_amurang1'
_IP_ = '10.7.1.116:33017' # '192.168.1.11:3306' # 
_LOCAL_IP_ = '192.168.1.11'

# _UNIT_CODE_ = "AMG1"
# _UNIT_NAME_ = "PLTU AMURANG (UNIT 1)"
# _DB_NAME_ = 'db_bat_amurang1'
# _IP_ = 'localhost:3307' 
# _LOCAL_IP_ = 'localhost'

_USER_ = 'root'
_PASS_ = 'P@ssw0rd'

WATCHDOG_INDICATOR = 2
COPT_BG_SLEEP_TIME = 5
RULE_SAFEGUARD = 20
CONSTRAIN_DESC_ML_LAST_RUN = "ML_LAST_RUN"
SKIP_FAN_AUTO = "SKIP_FAN_AUTO"
TEMP_FOLDER = 'data/temp/'

# COPT_BIAS_MIN = 2.0
# COPT_BIAS_MAX = 9.0
# COPT_OXY_MIN = 2.0
# COPT_OXY_MAX = 9.0

# SAFEGUARD_DCS = "SG_COPT1"
# SAFEGUARD_BAT = "COPT_SAFEGUARD"
# COPT_ENABLE = "COPT_ENABLE"
# COPT_RUN = "RUN_COPT1"
# COPT_OK = "COPT1_OK"
# COPT_ON = "COPT1_ON"
# COPT_SA_FAN = "AL81A101AM"
# COPT_PA_FAN = "ALAA101AMA"
# COPT_PA_BOOSTER = "AL13A101AM"
# COPT_ID_FAN = "A40A101AAM"
# COPT_OXY_LEFT = "ANA20CQ101"
# COPT_OXY_RIGHT = "ANA20CQ102"
# COPT_PERM_BIAS = "PRM_COPT1"
# COPT_OXY_IN = "O2_SV1"
# COPT_PRES_IN = "PRE_SA_IN1"
# COPT_LAMP_INDICATOR = "En_CO1"
# COPT_OXY_PV_IN = "O2_PVin1"
# RECOM_OXY = "Excess Oxygen"
# RECOM_PRESS = "SA Heater Out Press"

COPT_BIAS_MIN = 2
COPT_BIAS_MAX = 3
COPT_OXY_MIN = 4
COPT_OXY_MAX = 5
PARAM_DEBUG_MODE = 6

SAFEGUARD_DCS = 1
SAFEGUARD_BAT = 2
COPT_ENABLE = 3
COPT_RUN = 4
COPT_OK = 5
COPT_ON = 6
COPT_SA_FAN = 7
COPT_PA_FAN = 8
COPT_PA_BOOSTER = 9
COPT_ID_FAN = 10
COPT_OXY_LEFT = 11
COPT_OXY_RIGHT = 12
COPT_PERM_BIAS = 13
COPT_OXY_IN = 14
COPT_PRES_IN = 15
COPT_LAMP_INDICATOR = 16
COPT_OXY_PV_IN = 17
RECOM_OXY = 18
RECOM_PRESS = 19
CONSTRAIN_ID_COPT_ON = 20
CONSTRAIN_ID_ML_LAST_RUN = 21
CONSTRAIN_O2_SUGGEST = 22
SG_OXY_L=23
SG_OXY_R=24
COPT_COAL_IN=30
RECOM_COAL=31
CONSTRAIN_COAL_SUGGEST=32
CONSTRAIN_PRESS_SUGGEST=33
